version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '35432:5432'
    volumes:
      - database:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:8.5.10
    entrypoint: /bin/sh -c "while :; do sleep 10; done"
    volumes:
      - ./flyway:/flyway
    depends_on:
      - db

volumes:
  database:
    driver: local
